### ISSUE TITLE
TypeError: virtual is not a function when importing package using ESM

### ISSUE THREAD

**Issue by rghattas** [patak-dev/vite-plugin-virtual#9]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vite-plugin-virtual@0.2.0` for the project I'm working on.

I was seeing the following type error when running `vite build`:  `TypeError: virtual is not a function`
The vite.config.ts file was interpreting the imported file as a CommonJS module. I checked the `package.json `and looks like the exports are not properly configured to be compatible with ES Modules.
I patched the package.json on my end to return ESM when importing and CommonJS when requiring as a fix. Can we get this change shipped into main as well? Thanks!

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vite-plugin-virtual/package.json b/node_modules/vite-plugin-virtual/package.json
index 487ec58..2d0a40b 100644
--- a/node_modules/vite-plugin-virtual/package.json
+++ b/node_modules/vite-plugin-virtual/package.json
@@ -2,9 +2,16 @@
   "name": "vite-plugin-virtual",
   "description": "Virtual modules with HMR invalidation plugin for Vite",
   "version": "0.2.0",
-  "main": "dist/index.js",
-  "module": "dist/index.mjs",
-  "types": "index.d.ts",
+  "type": "module",
+  "main": "./dist/index.js",
+  "types": "./dist/index.d.ts",
+  "exports": {
+    ".": {
+      "types": "./dist/index.d.ts",
+      "import": "./dist/index.mjs",
+      "require": "./dist/index.js"
+    }
+  },
   "license": "MIT",
   "author": "patak-js <matias.capeletto@gmail.com>",
   "repository": {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by patak-dev** [comment]
Thanks! This should be fixed in 0.3.0
